# Generated by Django 4.2.3 on 2023-07-27 10:29

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('summary', models.TextField()),
                ('keywords', models.TextField()),
                ('refs', models.TextField()),
                ('date', models.DateTimeField()),
                ('url', models.TextField()),
                ('lang', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('summary', models.TextField()),
                ('keywords', models.TextField()),
                ('refs', models.TextField()),
                ('date', models.DateTimeField()),
                ('url', models.TextField()),
                ('lang', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'articles_list',
            },
        ),
    ]
