# Generated by Django 3.0.5 on 2023-07-26 08:28

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=400)),
                ('keywords', models.CharField(max_length=300)),
                ('refs', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
