# Generated by Django 4.2.3 on 2023-07-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('summary', models.TextField()),
                ('keywords', models.TextField()),
                ('refs', models.TextField()),
                ('date', models.DateTimeField()),
                ('url', models.TextField()),
                ('lang', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
