# Generated by Django 3.0.5 on 2023-07-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='refs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(),
        ),
    ]
