# Generated by Django 3.0.5 on 2023-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lang',
            field=models.IntegerField(null=True),
        ),
    ]
